import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { AssetsManifest } from "../types/assets";
import { createErrorRecord } from "../types/common";
import { generateSilentAudio } from "./audio-generator";
import { assertFfmpegAvailable, runFfmpeg, runFfprobe } from "./ffmpeg";
import { timelineDurationSeconds, totalTimelineSeconds, writeSrtForTimeline } from "./subtitle-renderer";
import {
  getTask,
  getTaskDir,
  getTaskOutputsDir,
  readTaskArtifact,
  resolveProjectPath,
  saveTask,
  setTaskStatus,
  toProjectRelativePath,
  writeTaskArtifact
} from "./task-store";
import { fileExists, generateMockSceneVideo } from "./video-generator";

function escapeConcatPath(filePath: string): string {
  return filePath.replaceAll("'", "'\\''");
}

function findTimelineItem(assets: AssetsManifest, sceneId: string) {
  return assets.timeline.find((item) => item.scene_id === sceneId);
}

async function ensureSceneVideos(taskId: string, assets: AssetsManifest): Promise<string[]> {
  const videoPaths: string[] = [];

  for (const asset of assets.assets) {
    if (asset.type !== "mock_video" && asset.type !== "placeholder") {
      continue;
    }

    const timelineItem = findTimelineItem(assets, asset.scene_id);
    const durationSeconds = timelineItem ? timelineDurationSeconds(timelineItem) : 4;
    if (!asset.file_path || !(await fileExists(asset.file_path))) {
      asset.file_path = await generateMockSceneVideo({
        taskId,
        sceneId: asset.scene_id,
        durationSeconds
      });
      asset.generation_status = "mocked";
      asset.provider = "mock";
      asset.description = `${asset.description} Regenerated locally as an FFmpeg mock placeholder.`;
    }

    videoPaths.push(resolveProjectPath(asset.file_path));
  }

  return videoPaths;
}

export async function mockAssembleForTask(taskId: string): Promise<AssetsManifest> {
  const task = await getTask(taskId);
  const assets = await readTaskArtifact<AssetsManifest>(taskId, "assets.json");
  assets.assemble_status = {
    ...assets.assemble_status,
    status: "mocked",
    note: "Mock assembly completed. No MP4 was generated; this is a reserved v0.3 entry point for FFmpeg/MoviePy/Remotion."
  };

  const { relativePath } = await writeTaskArtifact(taskId, "assets.json", assets);
  task.files.assets_json = relativePath;
  task.export_paths.mp4 = assets.assemble_status.mp4_reserved_path;
  setTaskStatus(task, "mocked", "assemble");
  await saveTask(task);
  return assets;
}

export async function assembleVideoForTask(taskId: string): Promise<AssetsManifest> {
  const task = await getTask(taskId);
  const assets = await readTaskArtifact<AssetsManifest>(taskId, "assets.json");
  const outputDir = getTaskOutputsDir(taskId);
  const finalDir = path.join(getTaskDir(taskId), "final");
  const finalVideoOnlyPath = path.join(finalDir, "video-only.mp4");
  const concatListPath = path.join(finalDir, "concat.txt");
  const outputPath = path.join(outputDir, "final.mp4");
  const outputRelativePath = toProjectRelativePath(outputPath);

  try {
    await assertFfmpegAvailable();
    await mkdir(finalDir, { recursive: true });
    await mkdir(outputDir, { recursive: true });

    const sceneVideoPaths = await ensureSceneVideos(taskId, assets);
    if (sceneVideoPaths.length === 0) {
      throw new Error("No mock scene video assets are available for assembly.");
    }

    await writeFile(
      concatListPath,
      sceneVideoPaths.map((filePath) => `file '${escapeConcatPath(filePath)}'`).join("\n"),
      "utf8"
    );

    await runFfmpeg([
      "-y",
      "-f",
      "concat",
      "-safe",
      "0",
      "-i",
      concatListPath,
      "-c",
      "copy",
      finalVideoOnlyPath
    ]);

    const subtitlePath = await writeSrtForTimeline(taskId, assets.timeline);
    const audioPath = await generateSilentAudio({
      taskId,
      durationSeconds: totalTimelineSeconds(assets.timeline)
    });

    const existingSilentAudio = assets.assets.find((asset) => asset.asset_id === "asset_silent_audio");
    if (existingSilentAudio) {
      existingSilentAudio.file_path = audioPath;
      existingSilentAudio.generation_status = "success";
    } else {
      assets.assets.push({
        asset_id: "asset_silent_audio",
        scene_id: "global",
        type: "voiceover",
        provider: "ffmpeg",
        file_path: audioPath,
        description: "Silent audio track generated by FFmpeg because no TTS or voiceover asset exists.",
        generation_status: "success"
      });
    }

    await runFfmpeg([
      "-y",
      "-i",
      finalVideoOnlyPath,
      "-i",
      resolveProjectPath(audioPath),
      "-map",
      "0:v:0",
      "-map",
      "1:a:0",
      "-c:v",
      "copy",
      "-c:a",
      "aac",
      "-shortest",
      "-movflags",
      "+faststart",
      outputPath
    ]);

    await runFfprobe(["-v", "error", "-show_format", "-show_streams", outputPath]);

    assets.assemble_status = {
      ...assets.assemble_status,
      status: "success",
      mode: "ffmpeg",
      mp4_reserved_path: outputRelativePath,
      mp4_path: outputRelativePath,
      subtitle_path: subtitlePath,
      audio_path: audioPath,
      note: "FFmpeg assembled a real MP4 from mock placeholder scene clips. The file is playable, but the visual content remains mock."
    };

    const { relativePath } = await writeTaskArtifact(taskId, "assets.json", assets);
    task.files.assets_json = relativePath;
    task.export_paths.mp4 = outputRelativePath;
    setTaskStatus(task, "success", "assemble");
    await saveTask(task);
    return assets;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    const errorRecord = createErrorRecord({
      step: "assemble",
      message,
      code: "FFMPEG_ASSEMBLE_FAILED",
      recoverable: true
    });
    assets.errors.push(errorRecord);
    assets.assemble_status = {
      ...assets.assemble_status,
      status: "failed",
      mode: "ffmpeg",
      mp4_reserved_path: outputRelativePath,
      note: `FFmpeg assembly failed: ${message}`
    };

    const { relativePath } = await writeTaskArtifact(taskId, "assets.json", assets);
    task.files.assets_json = relativePath;
    task.export_paths.mp4 = outputRelativePath;
    task.errors.push(errorRecord);
    setTaskStatus(task, "failed", "assemble");
    await saveTask(task);
    return assets;
  }
}
